### ISSUE TITLE
(May 5th) improve the user management component to enforce the userdata management policies defined in GDPR

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/UserManagement#9]

**Comment by cankarm** [comment]
Currently we reviewed the functionality of the components and which data is necessary to be stored/processed. The next step is categorizing this data and creating the consent. Meanwhile we have a consent for testing the SmartBoat application, where we will be able to get the template. In the last step all tasks for on-boarding and off-boarding the user will be defined and set for development.

**Comment by cankarm** [comment]
The GDPR consent is now almost finished. 

How we should tackle the user off-boarding in the users module? This means decommission of user's devices and  deleting users data. Sure all current computations should be moved to other places.

@rsucasas, are you the right person for this?

**Comment by sstanovnik** [comment]
Tasks left:
- enabling the deletion of the CIMI user through usermanagement's API
- adding a botan to the dashboard that triggers deletion of the user account
- at the registration step in the dashboard, the GDPR consent text and an "I agree" checkbox should be added

The first one is @rsucasas. I'm not sure who is responsible for the frontend; @cjdcordeiro any pointers? I'm also struggling to find the repository for it.

**Comment by cjdcordeiro** [comment]
for user registration UPC is in charge...

but there's no one in charge for the frontend in general. UPC is coordinating though

**Comment by sstanovnik** [comment]
Alex implemented consent and the deletion of the user account through the dashboard, so this is now done.

**Comment by cjdcordeiro** [comment]
does it include also the deletion of all other resources owned by that user? (devices, services, etc.)

**Comment by sstanovnik** [comment]
Apparently not, looking at https://github.com/mF2C/UserManagement/blob/f1cc585fd91cc94ca568b26a98ed716676c510d4/usermgnt/mF2C/data.py#L113

@rsucasas can you do this along with all other information owned by the user?

**Comment by sstanovnik** [comment]
Depends on mF2C/dataclay#38, as we can't actually delete objects, apparently. The user gets deleted (or at least is not visible in the list of users), I've tried that myself.

**Comment by alxjand** [comment]
Hi,
Im still using the xdelete cimi/api/user/{user} command Cris provided me months before to delete user accounts.
Is there any other "more advanced" command that allows me to delete not only the user but also all the user's devices info?

**Comment by sstanovnik** [comment]
That calls the user management component if I'm not mistaken. We decided a while ago that UM would handle deleting, so you don't have to do anything else if that's still true.

**Comment by alxjand** [comment]
Oke great :) thanks!
